version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: wedding_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Trungkiendeptrai12*
      POSTGRES_DB: Wedding_Management
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - wedding_network


  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: wedding_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    environment:
      DATABASE_URL: postgresql://postgres:Trungkiendeptrai12%2A@db:5432/Wedding_Management
    volumes:
      - ./uploads:/backend/uploads
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wedding_network
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: wedding_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - wedding_network
volumes:
  postgres_data:



networks:
  wedding_network:
    driver: bridge

